### ISSUE TITLE
iTunes recognizes files as video

### ISSUE THREAD

**Issue by ghost** [choffm/clean-m4a#1]
When cleaning purchased .m4a files with clean-m4a, iTunes recognizes the result as a video file. There is no chance to change it to music type within iTunes.

**Comment by Baumr** [comment]
Did you manage to find a workaround?

**Comment by ghost** [comment]
Unfortunately no... Still waiting for a fix / answer from author.

**Comment by choffm** [comment]
4179890a66326d7efdf90ba7eb90d676d0afa619

Sorry for the long waiting time. I figured out that mp4tags seems to  behave faulty when explicitly specifying the file type as "music". I removed that flag and on my machine, the cleaned files are recognized as music files. Please report again if the problem still occurs. Thanks!
