### ISSUE TITLE
Script removes genre from processed files and changes bit rate

### ISSUE THREAD

**Issue by Baumr** [choffm/clean-m4a#3]
I'm not sure why, but songs that have been processed by the script remove the genre field, and change the AAC bit rate to 258 kbps

Have you noticed that too?

**Comment by ghost** [comment]
Technically, the script does completely rebuild the tags. Unfortunately, the inserted tool 'mp4info' is not able to retrieve the genre, so it is lost after the process.

I can reproduce the bit rate thing, in my case it shows even 'Unknown' in iTunes. Let me do some checks. I'll report later.

**Comment by ghost** [comment]
I think there is no real issue regarding your bitrate observations. Music files purchased in iTunes Store are encoded in VBR with. approx. 256 kBit/s. After running through clean-m4a, iTunes shows a fixed value. In my test library it ranges from 258 to 285 kBit/s. Before the process, iTunes showed 256 kBit/s. If the files play fine in your player, you can consider this as a cosmetic issue.

**Comment by choffm** [comment]
The script does not parse the Genre tag as I don't think it's worth the effort. If you need genre tags, retag your files properly after running the script. While rewriting the tags, the real average  bitrate (instead of 256kb/s which is the target ABR) is computed. That's not an issue.

**Comment by Baumr** [comment]
That's a shame. Losing genre and having to re-do it manually will be cumbersome for me.

Thanks for letting me know, both.
